apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: my-prometheus
  labels:
    k8s-app: grafana
spec:
  selector:
    matchLabels:
      k8s-app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: my-prometheus
spec:
  type: NodePort
  ports:
    - name: http
      targetPort: http
      nodePort: 30080
      port: 3000
      protocol: TCP
  selector:
    k8s-app: grafana
