---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: main
  namespace: my-prometheus
  labels:
    prometheus: k8s
spec:
  replicas: 1
  version: v2.11.1
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-main
  namespace: my-prometheus
  labels:
    k8s-app: prometheus
spec:
  selector:
    matchLabels:
      k8s-app: prometheus
  endpoints:
    - port: web
      interval: 30s
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-main
  namespace: my-prometheus
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: main
