all:
  hosts:
    master:
      ansible_host: 192.168.2.241
      ip: 192.168.2.241
      access_ip: 192.168.2.241
    node1:
      ansible_host: 192.168.2.242
      ip: 192.168.2.242
      access_ip: 192.168.2.242
    node2:
      ansible_host: 192.168.2.243
      ip: 192.168.2.243
      access_ip: 192.168.2.243
    node3:
      ansible_host: 192.168.2.244
      ip: 192.168.2.244
      access_ip: 192.168.2.244
  children:
    kube-master:
      hosts:
        master:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        master:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
