all:
  hosts:
    master:
      ansible_host: 192.168.2.232
      ip: 192.168.2.232
      access_ip: 192.168.2.232
    node1:
      ansible_host: 192.168.2.233
      ip: 192.168.2.233
      access_ip: 192.168.2.233
    node2:
      ansible_host: 192.168.2.234
      ip: 192.168.2.234
      access_ip: 192.168.2.234
    node3:
      ansible_host: 192.168.2.235
      ip: 192.168.2.235
      access_ip: 192.168.2.235
  children:
    kube-master:
      hosts:
        master:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        master:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
